services:
  jurassic-world:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jurassicworld
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"